### ISSUE TITLE
lucid_cnn.py:328: RuntimeWarning: invalid value encountered in scalar divide

### ISSUE THREAD

**Issue by mma4194** [doriguzzi/lucid-ddos#10]
Hi, 
When I run the Inference on pcap files command, I get the following error:
![image](https://github.com/doriguzzi/lucid-ddos/assets/96077631/aecf1889-5f35-441f-8e68-c79d96f26512)

Also, the script runs for a while then killed. Would appreciate if you could assist in this. Thanks.

**Comment by doriguzzi** [comment]
Hi, 
that error is returned by the function ```report_results```, which computes the accuracy metrics.
This is because both TP and FN metrics are equal to zero. 
From the attached screenshot I can see that you are using a pcap file that is not part of the CIC-DDoS2019 dataset, therefore LUCID is not able to correctly compare the predicted labels with the ground truth. 
You should remove the option ```--dataset_type DOS2019``` and, if you know the IP addresses of the attack traffic, use the options ```--attack_net``` and ```--victim_net``` to allow LUCID to correctly compute the accuracy metrics of the predictions.

Hope this helps

--roberto
