### ISSUE TITLE
RuntimeWarning: invalid value encountered in long_scalars

### ISSUE THREAD

**Issue by abc744587** [doriguzzi/lucid-ddos#5]
Hello,
I used `PCAP detection` and `live traffic detection`, but when I press execute, it always displays `"RuntimeWarning: invalid value encountered in long_scalars"`, and ERR, F1, PPV, TPR are all displayed as 0, what is wrong? Thanks!!!!

![F1為零](https://user-images.githubusercontent.com/85470040/173237847-19d9ba9f-cf4c-471f-a3e0-89ab94958348.PNG)

**Comment by doriguzzi** [comment]
Hi, sorry for the late response. 
The error that you see is due to division by zero when computing the TPR and FNR metrics. Which means that both TP and FN are zero.
Since I see that the value of FPR is always equal to the DDoS%, your system is working as expected (the DDoS samples are classified as such, but the ground truth labels are wrong). So, the only problem is in the computation of the metrics that depend on the definition of attacker's and victim's IP addresses. I guess that you left them with the default values, which are defined in lucid_dataset_parser.py:

`CUSTOM_DDOS_SYN = {'attackers': ['11.0.0.' + str(x) for x in range(1,255)],
                      'victims': ['10.42.0.2']}`

You can change them here in the above dictionary with the IP addresses of your testbed, otherwise you can use the attack_net and victim_net parameters, as explained in the README.

Hope this helps.

--roberto
